CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    modified TIMESTAMPTZ NOT NULL DEFAULT now(),
    folderId INTEGER REFERENCES noteful_folders(id),
    content TEXT
);